[REF] pyproject.toml: set package-mode = false
Fixes
```
No dependencies to install or update

Installing the current project: oca-addons-repo-template (0.0.0)

Error: The current project could not be installed: No file/folder found for package oca-addons-repo-template
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
If you did intend to install the current project, you may need to set `packages` in your pyproject.toml file.
```

during `poetry install`